name: Deploy the page
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Provide personal access token
          TOKEN: ${{ secrets.REPO_PERMISSIONS }}